#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Customize to your needs...


# >>> coursier install directory >>>
export PATH="$PATH:/Users/paulb/Library/Application Support/Coursier/bin"
# <<< coursier install directory <<<
